---
- name: Set timezone to {{ timezone }}
  community.general.timezone:
    name: "{{ timezone }}"

- name: Do not install recommends and suggest by default
  template:
    src: templates/etc/apt/apt.conf.d/99recommend
    dest: /etc/apt/apt.conf.d/99recommend
    mode: 0644

- name: Uninstall ntp
  apt:
    name: ntp
    state: absent
    purge: true

- name: Ensure systemd-timesyncd is available on Debian 11 and Debian 12
  apt:
    name: systemd-timesyncd
    install_recommends: false
  when: ansible_distribution_major_version == '11' or ansible_distribution_major_version == '12'

- name: Enable systemd-timesyncd service
  systemd:
    name: systemd-timesyncd
    state: started
    enabled: true
  when: ansible_facts.virtualization_type not in ('docker', 'lxc', 'container', 'VirtualPC', 'containerd')

- name: Check if cloud-init has configured system
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloud_init_configured

- name: Change Hostname
  block:
    - name: change hostname
      hostname:
        name: "{{ hostname }}"

    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost {{ hostname }}'
        state: present
  when: not cloud_init_configured.stat.exists and (ansible_facts.virtualization_type not in ('docker', 'lxc', 'container', 'VirtualPC', 'containerd'))

- name: Update every package
  apt:
    name: '*'
    state: latest

- name: Install qemu-guest-agent
  apt:
    name: qemu-guest-agent
  register: qa_installation
  when: ansible_virtualization_role == 'guest' and (qemu_guest_agent | bool)
  notify: reboot

- name: Removing Debian 10 unneccessary packages
  apt:
    name: "{{ debian10_unnecessary_packages }}"
    state: absent
    autoremove: true
    purge: true
  when: ansible_distribution_major_version == '10'

- name: check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: reboot if required
  reboot:
    reboot_timeout: 600
  when: reboot_required.stat.exists

- name: Autoremove unneeded packages installed as dependencies
  apt:
    autoremove: true
    purge: true

- name: Install necessary packages to use sysctl
  apt:
    name: procps
    install_recommends: false

- name: Set vm.swappiness to 1 percent
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "1"
    state: present

- name: Increase local port range
  ansible.posix.sysctl:
    name: net.ipv4.ip_local_port_range
    value: "1025 65534"
    state: present
